name: kustomize-changes
description: find changes in flux kustomization trees 
inputs:
  # changes:
  #   description: 'changes to take into account'
  #   required: true
  # ref:
  #   description: 'git ref to compare to'
  #   required: true
  kustomizations-root:
    description: 'root directory containing kustomizations'
    # required: true
    default: .
  kustomizations:
    description: 'flux kustomization files'
    required: true
outputs:
  kustomization-changes:
    description: "kustomization roots that contain changes"
    value: ${{ steps.find_kustomization_changes.outputs.kustomization_changes }}
runs:
  using: "composite"
  steps:
    - run: echo "${{ github.action_path }}" >> $GITHUB_PATH
      shell: bash
    - name: find kustomization changes
      id: find_kustomization_changes
      shell: bash
      run: |
        changes=()
        changes+=(${{ inputs.changes }})
        echo "changes: $changes"
        kustomization_changes=$(get-kustomization-changes.sh ${{ inputs.kustomizations-root }} ${{ inputs.kustomizations }})
        echo "kustomization_changes: $kustomization_changes"
        echo "::set-output name=kustomization_changes::$kustomization_changes"
