name: github-checkruns
description: find changes in flux kustomization trees
inputs:
  github-token:
    required: true
  git-ref: 
    required: true
  kustomizations-root:
    description: 'root directory containing kustomizations'
    required: true
runs:
  using: "composite"
  steps:
    - run: echo "${{ github.action_path }}" >> $GITHUB_PATH
      shell: bash
    - name: find kustomization changes
      id: find_kustomization_changes
      shell: bash
      run: |
        flux-github-actions/github/github-checkruns/github-checkruns.sh ${{ inputs.github-token }} ${{ inputs.git-ref }} ${{ inputs.kustomizations-root }}
