name: find-kustomizations-with-policy-changes
description: find changes in policy folders
inputs:
  policy-root:
    description: 'root directory containing policies'
    default: .
outputs:
  kustomizations:
    description: "folders containing a policy subfolder with changes (up recursive)"
    value: ${{ steps.find_policy_changes.outputs.policy_folders }}
runs:
  using: "composite"
  steps:
    - run: echo "${{ github.action_path }}" >> $GITHUB_PATH
      shell: bash
    - name: find policy changes
      id: find_policy_changes
      shell: bash
      run: |
        policy_folders=$(find-policy-changes.sh ${{ inputs.policy-root }})
        echo "policy_folders: $policy_folders"
        echo "::set-output name=policy_folders::$policy_folders"
