    #!/bin/bash
set -e

DEFAULT_SEPARATOR=' '

kustomization_root="$1"
separator="${2:-$DEFAULT_SEPARATOR}"

result=()

kustomization_yml_find_pattern=".*/(Kustomization|kustomization\.ya?ml)$"
kustomization_yml_find_result=($(find $kustomization_root -maxdepth 1 -type f -regextype posix-extended -regex "$kustomization_yml_find_pattern"))

if [ ${#kustomization_yml_find_result[@]} -gt 1 ]; then
    >&2 echo "Error: Found multiple kustomization files under: $kustomization_root"
    exit 1
elif [[ ${#kustomization_yml_find_result[@]} -eq 1 ]]; then
    # >&2 echo "kustomization yml found: $kustomization_yml_find_result"
    while IFS= read -r resource; do
        if [[ "$resource" =~ .*.ya?ml$ ]]; then
            result+=("$kustomization_root/$resource")
        fi
    done <<<$(yq e -o=j -I=0 '.resources[]' "${kustomization_yml_find_result[0]}" | tr -d \")
else
    # autogenerated kustomization.yaml by flux including all yaml files in the current directory and all subdirectories
    yml_files=$(find $kustomization_root -regex ".*\.ya?ml$")
    while IFS= read -r yml_file; do
        if [[ ! -z "$yml_file" ]]; then
            result+=($yml_file)
        fi
    done <<< "${yml_files}"
fi

echo "${result[@]}" | tr "$separator" '\n' | sort -u | tr '\n' "$separator"






