name: conftest
description: execute conftest using policies in the parent directories
inputs:
  input:
    description: 'input file that will be validated with conftest'
    required: true
  root-directory:
    description: 'ancestor directory up to that policy subdirectories will be used'
    default: .
# outputs:
#   kustomization-changes:
#     description: "kustomization roots that contain changes"
#     value: ${{ steps.find_kustomization_changes.outputs.kustomization_changes }}
runs:
  using: "composite"
  steps:
    - run: echo "${{ github.action_path }}" >> $GITHUB_PATH
      shell: bash
    - name: execute conftest
      id: conftest
      shell: bash
      run: |
        conftest.sh ${{ inputs.input }} ${{ inputs.root-directory }}
