name: conftest
description: execute conftest using policies in the parent directories
inputs:
  files:
    description: 'files that will be validated with conftest'
    required: true
  policy-parent-directory-bottom:
    description: 'directory from that policy subdirectories will be used'
    required: true
  policy-parent-directory-top:
    description: 'ancestor directory up to that policy subdirectories will be used'
    default: .
runs:
  using: "composite"
  steps:
    - run: echo "${{ github.action_path }}" >> $GITHUB_PATH
      shell: bash
    - name: execute conftest
      id: conftest
      shell: bash
      run: |
        conftest.sh ${{ inputs.policy-parent-directory-top }} ${{ inputs.policy-parent-directory-bottom }} ${{ inputs.files }}
