name: find-kustomization-with-changes
description: find flux kustomization definitions with changes in their kustomization trees 
inputs:
  kustomizations-root:
    description: 'root directory containing kustomizations'
    default: .
  filename-pattern:
    description: pattern for relevant (changed) filenames
    default: .*?\.ya?ml
outputs:
  kustomizations:
    description: "kustomization roots that contain changes"
    value: ${{ steps.find_kustomization_changes.outputs.kustomizations }}
runs:
  using: "composite"
  steps:
    - run: echo "${{ github.action_path }}" >> $GITHUB_PATH
      shell: bash
    - name: find kustomization changes
      id: find_kustomization_changes
      shell: bash
      run: |
        kustomizations=$(find-kustomizations-with-changes.sh ${{ inputs.kustomizations-root }} "${{ inputs.filename-pattern }}")
        echo "kustomizations: $kustomizations"
        echo "::set-output name=kustomizations::$kustomizations"
