name: flux kustomize validation
description: validate kustomizations in a gitops repository 
inputs:
  github_token:
    description: 'github (app) token to create check run entries'
    required: true
  git_sha:
    description: 'git commit sha for check run entry'
    required: true
  kustomizations:
    description: 'kustomization directories to validate'
    required: true
  kustomization_root:
    description: 'root directory of all kustomizations'
    default: .
runs:
  using: "composite"
  steps:
    - run: echo "${{ github.action_path }}" >> $GITHUB_PATH
      shell: bash
    - name: validate
      shell: bash
      run: |
        validation.sh ${{ inputs.github_token }} ${{ inputs.git_sha }} ${{ inputs.kustomization_root }} ${{ inputs.kustomizations }}