name: validation
on:
  pull_request:
    branches:
      - main
jobs:
  validation:
    name: validation
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout flux-github-actions
        uses: actions/checkout@v3
      - name: install-conftest
        uses: ./conftest/install-conftest
      - name: unit tests
        id: unit-tests
        shell: bash
        run: |
          set -x
          github/create-checkrun/create-checkrun.sh ${{ secrets.GITHUB_TOKEN }} ${{ github.event.pull_request.head.sha }} conftest/conftest-test conftest/conftest-test/tests/tests.sh
          github/create-checkrun/create-checkrun.sh ${{ secrets.GITHUB_TOKEN }} ${{ github.event.pull_request.head.sha }} flux/find-kustomizations flux/find-kustomizations/tests/tests.sh
          github/create-checkrun/create-checkrun.sh ${{ secrets.GITHUB_TOKEN }} ${{ github.event.pull_request.head.sha }} flux/get-kustomization-path flux/get-kustomization-path/tests/tests.sh
          github/create-checkrun/create-checkrun.sh ${{ secrets.GITHUB_TOKEN }} ${{ github.event.pull_request.head.sha }} generic/filter-lists generic/filter-lists/tests/tests.sh
          github/create-checkrun/create-checkrun.sh ${{ secrets.GITHUB_TOKEN }} ${{ github.event.pull_request.head.sha }} generic/find-files generic/find-files/tests/tests.sh
          github/create-checkrun/create-checkrun.sh ${{ secrets.GITHUB_TOKEN }} ${{ github.event.pull_request.head.sha }} generic/find-in-ancestor-folders generic/find-in-ancestor-folders/tests/tests.sh
          github/create-checkrun/create-checkrun.sh ${{ secrets.GITHUB_TOKEN }} ${{ github.event.pull_request.head.sha }} kustomize/get-kustomization-resources kustomize/get-kustomization-resources/tests/tests.sh
          github/create-checkrun/create-checkrun.sh ${{ secrets.GITHUB_TOKEN }} ${{ github.event.pull_request.head.sha }} kustomize/get-kustomization-tree kustomize/get-kustomization-tree/tests/tests.sh

      - name: integation tests
        id: integration-tests
        shell: bash
        run: |
          github/create-checkrun/create-checkrun.sh ${{ secrets.GITHUB_TOKEN }} ${{ github.event.pull_request.head.sha }} integration-tests integration-tests/integration-test.sh

      - name: Checkout flux-github-actions-test
        uses: actions/checkout@v3
        with:
          path: flux-github-actions-test
          fetch-depth: 0
          repository: 'differenzierbar/flux-github-actions-test'
          ref: main
      - name: flux-github-actions-test
        id: flux-github-actions-test
        shell: bash
        run: |
          flux-github-actions/github/github-checkruns/github-checkruns.sh ${{ secrets.GITHUB_TOKEN }} 0ec447462b9b53f12ff7edd68345ed6f3d593aa0 flux-github-actions-test
