name: validation
on:
  pull_request:
    branches:
      - main
jobs:
  find:
    name: find
    runs-on: ubuntu-22.04
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - name: Checkout flux-github-actions
        uses: actions/checkout@v3
      - name: Checkout flux-github-actions-test
        uses: actions/checkout@v3
        with:
          path: flux-github-actions-test
          fetch-depth: 0
          repository: 'differenzierbar/flux-github-actions-test'
          ref: main
      - name: install
        run: |
          sudo apt-get install jq jo
      - name: find git changes
        id: find_git_changes
        uses: "./git/git-changes"
        with:
          ref: 0ec447462b9b53f12ff7edd68345ed6f3d593aa0 
          dir: ./flux-github-actions-test
      - name: find kustomization with changes
        id: find-kustomizations-with_changes
        uses: "./flux/find-kustomizations-with-changes"
        with:
          kustomizations-root: ./flux-github-actions-test
      - name: set matrix
        id: set-matrix
        run: |
          set -ex
          json_array=$(jo -a ${{ steps.find-kustomizations-with_changes.outputs.kustomizations }})
          if [[ $(echo $json_array | jq '. | length') -gt 0 ]]; then
            echo "::set-output name=matrix::{\"kustomization\": $json_array}"
          else 
            echo "::set-output name=matrix::"
          fi
  validation:
    needs: find
    runs-on: ubuntu-22.04
    if: ${{ needs.find.outputs.matrix != '' }}
    strategy:
      matrix: ${{fromJSON(needs.find.outputs.matrix)}}
    steps:
      - name: Checkout flux-github-actions
        uses: actions/checkout@v3
      - name: Checkout flux-github-actions-test
        uses: actions/checkout@v3
        with:
          path: flux-github-actions-test
          fetch-depth: 0
          repository: 'differenzierbar/flux-github-actions-test'
          ref: main
      - name: install-kustomize
        uses: ./kustomize/install-kustomize
      - name: install-conftest
        uses: ./conftest/install-conftest
      - name: generate kustomization yaml
        uses: "./kustomize/generate-kustomization-yaml"
        with: 
          directory: flux-github-actions-test/${{ matrix.kustomization }}
      - name: kustomize build
        id: kustomize_build
        run: |
          kustomize build flux-github-actions-test/${{ matrix.kustomization }} > flux-github-actions-test/${{ matrix.kustomization }}/kustomize_build_output.yaml
      - name: conftest-test
        id: conftest-test
        uses: "./conftest/conftest-test"
        with: 
          input: flux-github-actions-test/${{ matrix.kustomization }}/kustomize_build_output.yaml
          directory: flux-github-actions-test/${{ matrix.kustomization }}
          root-directory: flux-github-actions-test
