name: git-changes
description: find changes in a git repository 
inputs:
  ref:
    description: 'git ref to compare to'
    required: true
  dir: 
    default: .
# outputs:
#   git-changes:
#     description: "git merge-base HEAD inputs.ref) --name-only"
#     value: ${{ steps.find_git_changes.outputs.git_changes }}
runs:
  using: "composite"
  steps:
    # - run: echo "${{ github.action_path }}" >> $GITHUB_PATH
    #   shell: bash
    - name: find git changes
      id: find_git_changes
      shell: bash
      run: |
        cd ${{ inputs.dir }}
        git_changes=$(git diff $(git merge-base HEAD ${{ inputs.ref }}) --name-only)
        echo "git_changes: $git_changes"
        # echo "::set-output name=git_changes::$git_changes"        
        echo "GIT_CHANGES<<EOF" >> $GITHUB_ENV
        echo "$git_changes" >> $GITHUB_ENV
        echo "EOF" >> $GITHUB_ENV