name: git-changes
description: find changes in a git repository 
inputs:
  changes:
    description: 'git ref to compare to'
    required: true
outputs:
  kustomization-changes:
    description: "git merge-base HEAD origin/$GITHUB_BASE_REF) --name-only"
    value: ${{ steps.find_git_changes.outputs.git_changes }}
runs:
  using: "composite"
  steps:
    # - run: echo "${{ github.action_path }}" >> $GITHUB_PATH
    #   shell: bash
    - name: find git changes
      id: find_git_changes
      shell: bash
      run: |
        git_changes=$(git diff $(git merge-base HEAD origin/$GITHUB_BASE_REF) --name-only)
        echo "git_changes: $git_changes"
        echo "::set-output name=git_changes::$git_changes"        