name: get-kustomization-path
description: get path attribute of input kustomization files
inputs:
  kustomizations:
    required: true
outputs:
  kustomization-path:
    description: "flux kustomization path"
    value: ${{ steps.find_kustomizations.outputs.kustomization-path }}
runs:
  using: "composite"
  steps:
    - run: echo "${{ github.action_path }}" >> $GITHUB_PATH
      shell: bash
    - name: get-kustomization-path
      id: get-kustomization-path
      shell: bash
      run: |
        kustomization_path=$(get-kustomization-path.sh "${{ inputs.kustomizations }}")
        echo "kustomization_path: $kustomization_path"
        echo "::set-output name=kustomization-path::$kustomization_path"
